#!/usr/bin/env python

from yelp_servlib import serviceinitlib, uwsgi_serviceinit


if __name__ == "__main__":
    config = serviceinitlib.load_config(
        SERVICE='schematizer',
        PORT=65537,
        STATS_PORT=65538,
        NUM_WORKERS=4)

    actions = uwsgi_serviceinit.get_default_uwsgi_actions()
    serviceinitlib.run(config, actions)
